language: python
sudo: false
python:
- '3.6'
- '2.7'
install:
    - |
      if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
      "pip3 install -r requirements.txt"
      fi
    - |
      if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
      "pip install -r requirements.txt"
      fi
script:
- |
  if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
  sudo python3 setup.py install
  python3 test/test.py
  fi
- |
  if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
  sudo python setup.py install
  python test/test.py
  fi
