language: python
sudo: false
cache:
  pip: true
python:
- '3.6'
- '2.7'
install:
- "pip install -r requirements.txt"
script:
- sudo python setup.py install
- |
  if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
  python3 test/test.py
  fi
- |
  if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
  python test/test.py
  fi
